//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryAccounting.dbo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounting_Card
    {
        public int ID_Accounting_Card { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> ID_Inventory { get; set; }
        public Nullable<int> ID_Storage { get; set; }
        public Nullable<int> ID_Invoice { get; set; }
    
        public virtual Expenditure_Invoice Expenditure_Invoice { get; set; }
        public virtual Inventory Inventory { get; set; }
        public virtual Receipt_Invoice Receipt_Invoice { get; set; }
        public virtual Storage Storage { get; set; }
    }
}
