//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryAccounting.dbo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InventoryAccountingEntities : DbContext
    {
        public InventoryAccountingEntities()
            : base("name=InventoryAccountingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Expenditure_Inventory> Expenditure_Inventory { get; set; }
        public virtual DbSet<Expenditure_Invoice> Expenditure_Invoice { get; set; }
        public virtual DbSet<Position> Position { get; set; }
        public virtual DbSet<Receipt_Inventory> Receipt_Inventory { get; set; }
        public virtual DbSet<Receipt_Invoice> Receipt_Invoice { get; set; }
        public virtual DbSet<Storage> Storage { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Type_Inventory> Type_Inventory { get; set; }
        public virtual DbSet<Accounting_Card_Expenditure> Accounting_Card_Expenditure { get; set; }
        public virtual DbSet<Accounting_Card_Receipt> Accounting_Card_Receipt { get; set; }
        public virtual DbSet<Image_Inventory> Image_Inventory { get; set; }
        public virtual DbSet<Inventory> Inventory { get; set; }
    }
}
