//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryAccounting.dbo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expenditure_Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Expenditure_Invoice()
        {
            this.Expenditure_Inventory = new HashSet<Expenditure_Inventory>();
            this.Accounting_Card_Expenditure = new HashSet<Accounting_Card_Expenditure>();
        }
    
        public int ID_Expenditure_Invoice { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> ID_Employee { get; set; }
        public Nullable<int> ID_Storage { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expenditure_Inventory> Expenditure_Inventory { get; set; }
        public virtual Storage Storage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accounting_Card_Expenditure> Accounting_Card_Expenditure { get; set; }
    }
}
