//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryAccounting.dbo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inventory()
        {
            this.Accounting_Card_Expenditure = new HashSet<Accounting_Card_Expenditure>();
            this.Accounting_Card_Receipt = new HashSet<Accounting_Card_Receipt>();
            this.Expenditure_Inventory = new HashSet<Expenditure_Inventory>();
            this.Receipt_Inventory = new HashSet<Receipt_Inventory>();
        }
    
        public int ID_Inventory { get; set; }
        public string Name { get; set; }
        public Nullable<int> ID_Type_Inventory { get; set; }
        public string Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accounting_Card_Expenditure> Accounting_Card_Expenditure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accounting_Card_Receipt> Accounting_Card_Receipt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expenditure_Inventory> Expenditure_Inventory { get; set; }
        public virtual Type_Inventory Type_Inventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receipt_Inventory> Receipt_Inventory { get; set; }
    }
}
