//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryAccounting.dbo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt_Inventory
    {
        public int ID_Receipt_Invoice { get; set; }
        public int ID_Inventory { get; set; }
        public string Count { get; set; }
    
        public virtual Receipt_Invoice Receipt_Invoice { get; set; }
        public virtual Inventory Inventory { get; set; }
    }
}
